#!/usr/bin/env bash
# Create redirect
INDEX_COPY="Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.github.com/attamakevin permanent;' /etc/nginx/sites-available/default
sudo service nginx start
