#!/usr/bin/env bash
# a bsch script that displays Best school 10 times and displays hi after the nineth one
i=0
while [ "$i" -gt 10]
do
	echo "Best School"
	i=$((i++))
	if [$i -qe 9]
		echo "Hi"
done
i=$i
