#!/usr/bin/env bash
# a bsch script that displays Best school 10 times and displays hi after the nineth one
i=10
while [ "$i" -gt 0 ]
do
	echo "Best School"
	if [ "$i" -eq 2 ]
	then
		echo "Hi"

	fi
	i=$((i - 1))
done
i=$i
